services:
- docker:dind

ansible-2.8:
  extends: .template
  variables:
    ANSIBLE_VERSION: "2.8.*"
    MOLECULE_VERSION: "2.22"
    TAG: "ansible-2.8"

ansible-2.7:
  extends: .template
  variables:
    ANSIBLE_VERSION: "2.7.*"
    MOLECULE_VERSION: "2.22"
    TAG: "ansible-2.7"

.template:
  image: "docker:latest"
  variables:
    REPOSITORY_URL: "874811656702.dkr.ecr.us-east-1.amazonaws.com/docker-ansible-ci"
  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
  script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker build -t $REPOSITORY_URL:$TAG --build-arg $ANSIBLE_VERSION --build-arg $MOLECULE_VERSION .
    - docker push $REPOSITORY_URL:$TAG
  only:
    - master
  tags:
    - aws
